# Generated by Django 5.2.14 on 2026-09-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('medico', 'Médico Radiólogo'), ('recepcionista', 'Recepcionista'), ('administrador', 'Administrador')], default='recepcionista', max_length=20),
        ),
    ]
