# Generated by Django 5.2.14 on 2026-09-16 15:37

from django.db import migrations


def migrate_tecnico_to_recepcionista(apps, schema_editor):
    """Migra usuarios existentes con rol 'tecnico' a 'recepcionista'."""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(rol='tecnico').update(rol='recepcionista')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_rol'),
    ]

    operations = [
        migrations.RunPython(migrate_tecnico_to_recepcionista, migrations.RunPython.noop),
    ]
