# Generated by Django 5.2.14 on 2026-09-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_migrate_tecnico_to_recepcionista'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
