# Generated by Django 5.2.14 on 2026-06-03 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCNN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patologias', models.JSONField()),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('tiempo_inferencia_seg', models.FloatField(null=True)),
                ('imagen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_cnn', to='estudios.imagendicom')),
            ],
        ),
    ]
