# Generated by Django 5.2.14 on 2026-06-03 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformePreliminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnica', models.TextField(default='Radiografía de Tórax PA. Técnica digital.')),
                ('hallazgos', models.TextField(blank=True)),
                ('impresion', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revisado', 'Revisado'), ('firmado', 'Firmado')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_firmado', models.DateTimeField(blank=True, null=True)),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe', to='pacientes.estudio')),
                ('medico', models.ForeignKey(blank=True, limit_choices_to={'rol': 'medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
