# Generated by Django 5.2.14 on 2026-09-16 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('architecture', models.CharField(default='resnet50', max_length=100)),
                ('checkpoint_path', models.CharField(max_length=500)),
                ('classes', models.JSONField(default=list)),
                ('thresholds', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_name', models.CharField(blank=True, max_length=100)),
                ('train_config', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilities', models.JSONField(default=dict)),
                ('thresholds', models.JSONField(default=dict)),
                ('findings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inference_time_ms', models.FloatField(blank=True, null=True)),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='neorx.aimodel')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='pacientes.estudio')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estudio', 'created_at'], name='neorx_aipre_estudio_f0de0e_idx'), models.Index(fields=['ai_model', 'created_at'], name='neorx_aipre_ai_mode_fa63c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('create', 'Crear'), ('read', 'Leer'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Exportar'), ('firmar', 'Firmar informe'), ('diagnostico', 'Ejecutar diagnóstico')], db_index=True, max_length=20)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='neorx_audit_user_id_0626c6_idx'), models.Index(fields=['resource_type', 'resource_id'], name='neorx_audit_resourc_b8ab07_idx'), models.Index(fields=['action', 'timestamp'], name='neorx_audit_action_7a1659_idx')],
            },
        ),
    ]
