# Generated by Django 5.2.14 on 2026-09-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neorx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Crear'), ('read', 'Leer'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Exportar'), ('firmar', 'Firmar informe'), ('diagnostico', 'Ejecutar diagnóstico'), ('gradcam', 'Generar Grad-CAM'), ('process', 'Procesar imagen'), ('validate', 'Validar calidad de imagen')], db_index=True, max_length=20),
        ),
    ]
