import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, X, ArrowUpRight } from 'lucide-react'
import { useAuth } from '../context/useAuth'
import { useFilters, useResource } from '../hooks/useWorkspace'
import { Filter, ResetFilters, Pagination, ResourceState, Status } from '../components/ui/WorkspaceUI'
export default function EstudiosPage({pending = false}) {
  const {rol} = useAuth()
  const {filters, setFilter, reset} = useFilters({page:'1', page_size:'20', ordering:'-created_at', ...(pending ? {cola:'informes'} : {})})
  const [revision,setRevision] = useState(0), [selected,setSelected] = useState(null)
  const {data,loading,error} = useResource('/pacientes/estudios/',filters,revision)
  const rows = data?.results || []
  return <div className="workspace"><header className="page-heading"><div><h1>{pending ? 'Pendientes' : 'Estudios'}</h1><p>{pending ? 'Seguimiento de informes, procesamiento y repeticiones técnicas.' : 'Consulte los estudios y el estado de sus informes.'}</p></div>{rol !== 'administrador' && <Link className="btn-primary" to="/escaneo"><Plus size={18}/>Nuevo estudio</Link>}</header>
    {pending && <div className="tabs" aria-label="Tipo de pendiente">{[['informes','Informes sin firmar'],['procesamiento','Por procesar'],['errores','Errores de procesamiento'],['repeticion','Repetición técnica']].map(([value,label]) => <button key={value} aria-pressed={filters.cola===value} onClick={() => setFilter('cola',value)}>{label}</button>)}</div>}
    <section className="filters" aria-label="Filtros de estudios"><Filter label="Paciente o estudio" name="search" value={filters.search} onChange={setFilter} placeholder="Nombre, CI o tipo de estudio"/>{!pending && <Filter label="Estado" name="estado" value={filters.estado} onChange={setFilter}><option value="">Todos</option><option value="pendiente">Pendiente</option><option value="en_proceso">En proceso</option><option value="completado">Completado</option><option value="requiere_repeticion">Repetición técnica</option></Filter>}<Filter label="Registrado desde" name="fecha_desde" type="date" value={filters.fecha_desde} onChange={setFilter}/><Filter label="Registrado hasta" name="fecha_hasta" type="date" value={filters.fecha_hasta} onChange={setFilter}/><Filter label="Orden" name="ordering" value={filters.ordering} onChange={setFilter}><option value="-created_at">Más recientes</option><option value="created_at">Más antiguos</option><option value="-fecha">Fecha del estudio</option></Filter><ResetFilters onClick={reset}/></section>
    {selected && <section className="panel" aria-label="Detalle del estudio"><div className="panel-heading"><h2>Estudio #{selected.id}</h2><button className="btn-secondary px-3" onClick={() => setSelected(null)} aria-label="Cerrar detalle"><X size={18}/></button></div><dl className="grid sm:grid-cols-2 gap-4 p-6 text-sm"><div><dt className="text-slate-600">Paciente</dt><dd className="font-semibold mt-1">{selected.paciente_nombre}</dd></div><div><dt className="text-slate-600">Tipo y fecha</dt><dd className="mt-1">{selected.tipo_estudio} · {selected.fecha}</dd></div><div><dt className="text-slate-600">Estado</dt><dd className="mt-1"><Status value={selected.estado}/></dd></div><div><dt className="text-slate-600">Informe</dt><dd className="mt-1"><Status value={selected.informe_estado}/></dd></div><div className="sm:col-span-2"><dt className="text-slate-600">Observaciones</dt><dd className="mt-1 whitespace-pre-wrap">{selected.observaciones || 'Sin observaciones registradas.'}</dd></div></dl><div className="px-6 pb-6 flex flex-wrap gap-3">{selected.ultima_imagen_id && <Link className="btn-primary" to={`/analisis/${selected.id}`}>Ver radiografía y análisis<ArrowUpRight size={16}/></Link>}{rol === 'medico' && selected.informe_id && <Link className="btn-secondary" to={`/informes/${selected.informe_id}`}>Abrir informe</Link>}{!selected.ultima_imagen_id && rol !== 'administrador' && <Link className="btn-secondary" to={`/escaneo?paciente=${selected.paciente}`}>Cargar radiografía</Link>}</div></section>}
    <ResourceState loading={loading} error={error} empty={!rows.length} onRetry={() => setRevision(v=>v+1)}><section className="panel"><div className="table-scroll"><table className="data-table"><thead><tr>{['Paciente','Estudio','Fecha','Estado','Informe','Acciones'].map(v=><th key={v} scope="col">{v}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td className="font-semibold text-navy">{row.paciente_nombre}<p className="text-xs text-slate-600 font-normal mt-1">Estudio #{row.id}</p></td><td>{row.tipo_estudio}</td><td className="whitespace-nowrap">{row.fecha}</td><td><Status value={row.estado}/></td><td><Status value={row.informe_estado}/></td><td><button className="btn-secondary whitespace-nowrap" onClick={() => setSelected(row)}>Ver detalle<span className="sr-only"> del estudio {row.id}</span></button></td></tr>)}</tbody></table></div><Pagination page={filters.page} pageSize={filters.page_size} total={data?.count || 0} onChange={setFilter}/></section></ResourceState>
  </div>
}
