# Generated by Django 5.2.14 on 2026-06-03 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenDICOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_dicom', models.FileField(upload_to='dicom/%Y/%m/')),
                ('archivo_png', models.FileField(blank=True, null=True, upload_to='png/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('es_nitida', models.BooleanField(null=True)),
                ('varianza_laplaciana', models.FloatField(null=True)),
                ('estado_procesamiento', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='pacientes.estudio')),
            ],
        ),
    ]
