# Generated by Django 5.2.14 on 2026-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagendicom',
            name='proyeccion_fuente',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imagendicom',
            name='tipo_proyeccion',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
